import logging
import json
import config
import aiohttp
from curl_cffi.requests import AsyncSession 

logger = logging.getLogger(__name__)

class AudioStudio:
    def __init__(self):
        self.eleven_key = config.ELEVENLABS_API_KEY
        self.openai_key = config.OPENAI_API_KEY
        
        self.eleven_url = "https://api.elevenlabs.io/v1"
        self.openai_url = "https://api.openai.com/v1/audio/speech"
        
        # Маскировка для ElevenLabs
        self.headers_eleven = {
            "xi-api-key": self.eleven_key,
            "Content-Type": "application/json",
            "Accept": "audio/mpeg",
            "Origin": "https://elevenlabs.io",
            "Referer": "https://elevenlabs.io/"
        }

        # Карта соответствия голосов (ElevenLabs -> OpenAI)
        self.voice_map = {
            config.VOICE_ADAM: "onyx",    # Мужской глубокий
            config.VOICE_RACHEL: "nova",  # Женский спокойный
            config.VOICE_FIN: "echo",     # Мужской энергичный
            config.VOICE_MIMI: "shimmer"  # Высокий/Детский
        }
        
    async def text_to_speech(self, text, voice_id):
        """Пробует ElevenLabs, если неудача — использует OpenAI"""
        
        # 1. Попытка через ElevenLabs (Приоритет)
        if self.eleven_key:
            audio = await self._try_elevenlabs(text, voice_id)
            if audio: return audio
            
        logger.warning("⚠️ ElevenLabs недоступен (IP Block). Переключаюсь на резервный канал (OpenAI)...")
        
        # 2. Резервный канал (OpenAI)
        return await self._try_openai(text, voice_id)

    async def _try_elevenlabs(self, text, voice_id):
        url = f"{self.eleven_url}/text-to-speech/{voice_id}?output_format=mp3_44100_128"
        payload = {
            "text": text,
            "model_id": "eleven_multilingual_v2", 
            "voice_settings": {"stability": 0.5, "similarity_boost": 0.75}
        }
        
        try:
            async with AsyncSession(impersonate="chrome124") as session:
                resp = await session.post(url, json=payload, headers=self.headers_eleven)
                
                if resp.status_code == 200:
                    content = resp.content
                    # Проверка на капчу или ошибку
                    if content.strip().startswith(b"<") or len(content) < 100:
                        logger.error("ElevenLabs: Cloudflare Captcha detected.")
                        return None
                    logger.info(f"✅ TTS: Generated by ElevenLabs ({len(content)} bytes)")
                    return content
                else:
                    logger.error(f"ElevenLabs Error {resp.status_code}")
                    return None
        except Exception as e:
            logger.error(f"ElevenLabs Connection Error: {e}")
            return None

    async def _try_openai(self, text, eleven_voice_id):
        """Генерация через OpenAI (Fallback)"""
        if not self.openai_key:
            logger.error("OpenAI API Key missing for fallback.")
            return None

        # Подбираем похожий голос
        openai_voice = self.voice_map.get(eleven_voice_id, "alloy")
        
        headers = {"Authorization": f"Bearer {self.openai_key}", "Content-Type": "application/json"}
        payload = {
            "model": "tts-1",
            "input": text,
            "voice": openai_voice
        }
        
        try:
            async with aiohttp.ClientSession() as session:
                async with session.post(self.openai_url, json=payload, headers=headers) as resp:
                    if resp.status == 200:
                        content = await resp.read()
                        logger.info(f"✅ TTS: Generated by OpenAI (Fallback) - Voice: {openai_voice}")
                        return content
                    else:
                        error = await resp.text()
                        logger.error(f"OpenAI TTS Error {resp.status}: {error}")
                        return None
        except Exception as e:
            logger.error(f"OpenAI TTS Critical: {e}")
            return None

    async def generate_sfx(self, description, duration_seconds=None):
        """SFX пока только через ElevenLabs"""
        if not self.eleven_key: return None
        url = f"{self.eleven_url}/sound-generation"
        payload = {"text": description, "duration_seconds": duration_seconds, "prompt_influence": 0.3}
        
        try:
            async with AsyncSession(impersonate="chrome124") as session:
                resp = await session.post(url, json=payload, headers=self.headers_eleven)
                if resp.status_code == 200 and not resp.content.startswith(b"<"):
                    return resp.content
                return None
        except Exception:
            return None

# Создаем синглтон
audio_studio = AudioStudio()
